"""
MuDAG-Pro global rule R_1 validator, filter, and rule-handbook exporter (Sections 3.3 and 3.4 of the paper).

Responsibilities:
1. Validate endpoints (filter hallucinated pathways outside the pool of 331 predefined pathway nodes).
2. Remove self-loops and duplicate edges.
3. Resolve direction conflicts (prefer rules with higher confidence).
4. Detect and remove cycles (T_acyclic algorithm).
5. Export the frozen global rule handbook rules_handbook.json (containing 34 cross-branch regulatory edges).

Global rule R_1 generation workflow from Section 3.3 of the paper:
    R_0 → endpoint validation → deduplication and merging → conflict resolution → cycle detection → R_1
"""
import json
import os
import numpy as np
from typing import List, Dict, Set, Tuple, Optional
from collections import defaultdict


class RuleHandbookGenerator:
    """
    Global rule R_1 validator, filter, and rule-handbook exporter (Sections 3.3 and 3.4 of the paper).

    Validates endpoints, removes hallucinated pathways, filters cycles,
    and exports the frozen rules_handbook.json.
    """
    def __init__(self, pathway_names: List[str]):
        """
        Args:
            pathway_names: List of M=331 core pathway names (allowlist).
        """
        self.pathway_names = pathway_names
        self.valid_pathways: Set[str] = set(pathway_names)
        self.M = len(pathway_names)
        self.p2idx = {name: i for i, name in enumerate(pathway_names)}

    def filter_and_export(
        self,
        raw_rules: List[Dict],
        output_json_path: str,
        baseline_edges: Optional[Set[Tuple[str, str]]] = None,
    ) -> List[Dict]:
        """
        Complete rule-refinement pipeline: filter initial rule set R_0 to generate global rule set R_1 (Section 3.3 of the paper).

        Filtering logic:
        1. Filter hallucinated pathway nodes outside the pool of 331 predefined pathway nodes.
        2. Remove self-loops (source == target) and duplicate edges.
        3. Resolve direction conflicts (retain the more reliable edge based on confidence).
        4. Detect and remove cycles (T_acyclic).
        5. Ensure the complete tuple is present (source, target, gene, delta, pmid, confidence).

        Args:
            raw_rules: Initial rule set R_0 generated by the LLM.
            output_json_path: Output JSON file path.
            baseline_edges: Baseline DAG edge set {(src, tgt), ...} (used for cycle detection).

        Returns:
            valid_rules: Filtered global rule handbook R_1.
        """
        print(f"[Rule Generator] Initial rule count: {len(raw_rules)}")

        # Step 1: Validate endpoints.
        rules = self._filter_invalid_endpoints(raw_rules)
        print(f"[Rule Generator] After endpoint validation: {len(rules)}")

        # Step 2: Remove self-loops and duplicate edges.
        rules = self._deduplicate_and_remove_selfloops(rules)
        print(f"[Rule Generator] After dedup: {len(rules)}")

        # Step 3: Resolve direction conflicts.
        rules = self._resolve_direction_conflicts(rules)
        print(f"[Rule Generator] After conflict resolution: {len(rules)}")

        # Step 4: Detect and remove cycles.
        if baseline_edges:
            rules = self._detect_and_remove_cycles(rules, baseline_edges)
            print(f"[Rule Generator] After cycle detection: {len(rules)}")

        # Step 5: Sort by confidence in descending order.
        rules.sort(key=lambda r: r.get("confidence", 0), reverse=True)

        # Save and freeze as rules_handbook.json.
        os.makedirs(os.path.dirname(output_json_path), exist_ok=True)
        with open(output_json_path, "w", encoding="utf-8") as f:
            json.dump(rules, f, indent=2, ensure_ascii=False)

        print(f"[Rule Generator] Successfully exported {len(rules)} global regulatory rules to: {output_json_path}")
        return rules

    def _filter_invalid_endpoints(self, rules: List[Dict]) -> List[Dict]:
        """
        Validate endpoints (Step iii in Section 3.3 of the paper).

        Filter:
        - Rules whose source or target is outside the pool of 331 core pathways.
        - Self-loops (source == target).
        """
        valid_rules = []
        for r in rules:
            src = r.get("source", "")
            tgt = r.get("target", "")

            # Check node validity.
            if src not in self.valid_pathways:
                print(f"[Rule Filter] Discarded: source pathway '{src}' not in core pathway pool")
                continue
            if tgt not in self.valid_pathways:
                print(f"[Rule Filter] 舍弃: 靶通路 '{tgt}' 不在核心通路池中")
                continue

            # Check for self-loops.
            if src == tgt:
                print(f"[Rule Filter] 舍弃: 自环边 '{src}' -> '{tgt}'")
                continue

            valid_rules.append(r)

        return valid_rules

    def _deduplicate_and_remove_selfloops(self, rules: List[Dict]) -> List[Dict]:
        """
        Deduplicate and merge (Step iii in Section 3.3 of the paper).

        Deduplicate by the (source, target, gene) triplet,
        merging multiple rules with the same triplet into one (weighted-mean delta and maximum confidence).
        """
        groups: Dict[Tuple[str, str, str], List[Dict]] = defaultdict(list)
        for r in rules:
            key = (r["source"], r["target"], r.get("gene", ""))
            groups[key].append(r)

        merged_rules = []
        for (src, tgt, gene), group in groups.items():
            if len(group) == 1:
                merged_rules.append(group[0])
            else:
                # Merge: confidence-weighted mean of delta.
                total_conf = sum(r.get("confidence", 0.5) for r in group)
                if total_conf == 0:
                    total_conf = 1.0

                weighted_delta = sum(
                    r.get("delta", 1.0) * r.get("confidence", 0.5)
                    for r in group
                ) / total_conf

                avg_confidence = total_conf / len(group)

                # Collect PMIDs.
                pmids = list(set(r.get("pmid", "") for r in group if r.get("pmid")))
                pmid_str = "; ".join(pmids)

                merged = {
                    "source": src,
                    "target": tgt,
                    "gene": gene,
                    "delta": round(weighted_delta, 4),
                    "pmid": pmid_str,
                    "confidence": round(min(avg_confidence * 1.1, 1.0), 4),
                }
                merged_rules.append(merged)

        return merged_rules

    def _resolve_direction_conflicts(self, rules: List[Dict]) -> List[Dict]:
        """
        Resolve direction conflicts (Step iii in Section 3.3 of the paper).

        When both (j→k) and (k→j) exist, retain the one with higher confidence.
        Principle from the paper: use confidence score c to prioritize the regulatory direction with stronger literature evidence.
        """
        rule_dict: Dict[Tuple[str, str], Dict] = {}
        removed_count = 0

        for rule in rules:
            key = (rule["source"], rule["target"])
            rev_key = (rule["target"], rule["source"])

            if rev_key in rule_dict:
                # A direction conflict was found.
                existing = rule_dict[rev_key]
                if rule["confidence"] > existing["confidence"]:
                    # The current rule has higher confidence; replace the reverse edge.
                    del rule_dict[rev_key]
                    rule_dict[key] = rule
                    print(f"[Rule Filter] 方向冲突: 保留 '{rule['source']}' -> '{rule['target']}' "
                          f"(c={rule['confidence']:.2f}), "
                          f"舍弃反向边 (c={existing['confidence']:.2f})")
                    removed_count += 1
                else:
                    print(f"[Rule Filter] 方向冲突: 保留已有边 "
                          f"(c={existing['confidence']:.2f}), "
                          f"舍弃 '{rule['source']}' -> '{rule['target']}' "
                          f"(c={rule['confidence']:.2f})")
                    removed_count += 1
            else:
                rule_dict[key] = rule

        if removed_count > 0:
            print(f"[Rule Filter] 共消解 {removed_count} 个方向冲突")

        return list(rule_dict.values())

    def _detect_and_remove_cycles(
        self,
        rules: List[Dict],
        baseline_edges: Set[Tuple[str, str]],
    ) -> List[Dict]:
        """
        Detect and remove cycles (T_acyclic in Sections 3.3 and 3.4 of the paper).

        Merge candidate rule edges with baseline DAG edges and detect whether cycles are introduced.
        If a cycle is introduced, preferentially remove the lowest-weight rule edge by confidence to break it.

        Detect cycles with three-color DFS marking.
        """
        # Build the union graph containing baseline and candidate-rule edges.
        adjacency: Dict[str, Set[Tuple[str, Optional[Dict]]]] = {
            name: set() for name in self.valid_pathways
        }

        # Add baseline edges.
        for src, tgt in baseline_edges:
            if src in adjacency and tgt in adjacency:
                adjacency[src].add((tgt, None))

        # Add candidate-rule edges.
        rule_map: Dict[Tuple[str, str], Dict] = {}
        for rule in rules:
            src, tgt = rule["source"], rule["target"]
            if src in adjacency and tgt in adjacency:
                adjacency[src].add((tgt, rule))
                rule_map[(src, tgt)] = rule

        # DFS cycle detection.
        removed_edges: Set[Tuple[str, str]] = set()
        max_iterations = 100  # Safety valve.
        iteration = 0

        while iteration < max_iterations:
            iteration += 1
            cycle_edges = self._find_cycle_dfs(adjacency)

            if not cycle_edges:
                break

            # Find and remove the rule edge with the lowest confidence.
            min_conf = float('inf')
            edge_to_remove = None

            for src, tgt, rule in cycle_edges:
                if rule is not None:
                    conf = rule.get("confidence", 0.5)
                    if conf < min_conf:
                        min_conf = conf
                        edge_to_remove = (src, tgt, rule)

            if edge_to_remove is not None:
                src, tgt, rule = edge_to_remove
                print(f"[Rule Filter] 环路检测: 删除边 '{src}' -> '{tgt}' "
                      f"(confidence={rule.get('confidence', 0.5):.2f})")
                removed_edges.add((src, tgt))

                # Remove it from the adjacency list.
                adjacency[src] = {
                    (t, r) for t, r in adjacency[src]
                    if not (t == tgt and r is rule)
                }
            else:
                # The cycle consists only of baseline edges (rare case).
                print("[Rule Filter] 警告: 基线 DAG 中存在环路，跳过")
                break

        # Return rules that were not removed.
        return [
            r for r in rules
            if (r["source"], r["target"]) not in removed_edges
        ]

    def _find_cycle_dfs(
        self,
        adjacency: Dict[str, Set[Tuple[str, Optional[Dict]]]],
    ) -> List[Tuple[str, str, Optional[Dict]]]:
        """
        Detect the set of cycle edges in a directed graph using three-color DFS marking.

        WHITE (0): Unvisited.
        GRAY (1): Currently being visited (in the current recursion stack).
        BLACK (2): Visit complete.
        """
        WHITE, GRAY, BLACK = 0, 1, 2
        color = {name: WHITE for name in adjacency}
        parent: Dict[str, Optional[str]] = {}

        def dfs(u: str) -> Optional[List[Tuple[str, str, Optional[Dict]]]]:
            color[u] = GRAY
            for v, rule in adjacency.get(u, set()):
                if color[v] == GRAY:
                    # A cycle was found; build the list of cycle edges.
                    cycle = [(u, v, rule)]
                    cur = u
                    while parent.get(cur) is not None:
                        prev = parent[cur]
                        # Find the prev -> cur edge.
                        for vv, rr in adjacency.get(prev, set()):
                            if vv == cur:
                                cycle.append((prev, cur, rr))
                                break
                        cur = prev
                        if cur == v:
                            break
                    return cycle
                elif color[v] == WHITE:
                    parent[v] = u
                    result = dfs(v)
                    if result is not None:
                        return result
            color[u] = BLACK
            return None

        for node in adjacency:
            if color[node] == WHITE:
                result = dfs(node)
                if result is not None:
                    return result

        return []


def load_rules_handbook(json_path: str) -> List[Dict]:
    """Load the globally frozen rule handbook R_1."""
    if not os.path.exists(json_path):
        print(f"Warning: 规则手册 {json_path} 不存在")
        return []
    with open(json_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def extract_baseline_edges_from_adj(
    adj_matrix: np.ndarray,
    pathway_names: List[str],
) -> Set[Tuple[str, str]]:
    """
    Extract an edge set from an adjacency matrix (for cycle detection).

    Args:
        adj_matrix: Adjacency matrix A in R^(M x M).
        pathway_names: List of pathway names.

    Returns:
        edges: {(source_pathway, target_pathway), ...}
    """
    edges = set()
    M = adj_matrix.shape[0]
    for u in range(M):
        for v in range(M):
            if u != v and adj_matrix[u, v] > 0:
                u_name = pathway_names[u] if u < len(pathway_names) else f"P{u}"
                v_name = pathway_names[v] if v < len(pathway_names) else f"P{v}"
                edges.add((u_name, v_name))
    return edges
